version: "3.7"
services:
#  api:
#    container_name: short-url-api
#    image: short-url-api
#    build:
#      dockerfile: Dockerfile
#      context: .
#    ports:
#      - "3004:3004"
#    depends_on:
#      - db
#      - redis
#    links:
#      - db
#      - redis
#    volumes:
#      - ./:/src
#    command: npm run start:dev
#    env_file: .env
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DB_HOST: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:${REDIS_PORT}
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local